sudo: required

services:
    - docker

before_install:
    - mkdir -p src/vendor

    - git clone https://github.com/toggle-corp/react-store.git src/vendor/react-store
    - git --git-dir=src/vendor/react-store/.git --no-pager show --pretty=fuller --quiet
    - cp src/vendor/react-store/stylesheets/_user-imports-sample.scss src/vendor/react-store/stylesheets/_user-imports.scss

    - git clone https://github.com/toggle-corp/ravl.git src/vendor/ravl
    - git --git-dir=src/vendor/ravl/.git --no-pager show --pretty=fuller --quiet

    - docker pull devtc/dfid:latest
    - docker build --cache-from devtc/dfid:latest --tag devtc/dfid:latest .

before_script:
    - echo 'before_script'

script:
    - ./scripts/travis_deploy.sh

after_success:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push devtc/dfid:latest

deploy:
  provider: surge
  project: ./build/
  domain: dfid.surge.sh
  on: feature-deploy
