version: '3.2'

services:
    react:
        image: devtc/dfid:latest
        build:
          context: .
          cache_from:
            - devtc/dfid:latest
        env_file:
            - .env
        environment:
            - REACT_APP_API_HTTPS=https
        command: ['/code/scripts/run_develop.sh']
        volumes:
            - .:/code
        ports:
            - '3003:3000'
